### ISSUE TITLE
StreamingAsrManager causes data race compilation error with Xcode 26.4

### ISSUE THREAD

**Issue by macayer** [FluidInference/FluidAudio#425]
Summary
After updating from Xcode 26.3 to 26.4, FluidAudio fails to compile with a Swift strict concurrency data race error in StreamingAsrManager. Xcode 26.4 appears to default Strict Concurrency Checking to Complete, which flags the mutable asrManager property being accessed across async boundaries.

Environment
FluidAudio: latest main
Xcode: 26.4
Platform: iOS
Integration: Swift Package Manager inside an Xcode app project
Swift version: 5.9

Errors
Sending 'asrManager' risks causing data races

Steps to reproduce
Add FluidAudio to an iOS app via Swift Package Manager.
Update Xcode to 26.4.
Build the project.
The build fails with the data race error above.
Expected behavior
The project should compile successfully.

Actual behavior
Build fails due to strict concurrency checking flagging asrManager in StreamingAsrManager as unsafe across async boundaries.

Additional context
This does not occur on Xcode 26.3. The issue is that Xcode 26.4 changed the default for Strict Concurrency Checking from Minimal to Complete. Setting SWIFT_STRICT_CONCURRENCY = minimal at the project level does not help since SPM packages are built with their own settings.

A potential fix would be to mark the property as nonisolated(unsafe), make the type @unchecked Sendable, or wrap it in an actor.

**Comment by Alex-Wengg** [comment]
Hi @macayer. This issue should now be fixed in v0.12.6 via PR #419, where we converted AsrManager to an actor for Swift 6 concurrency safety. We had a discussion about this in this issue https://github.com/FluidInference/FluidAudio/issues/415 .


If you're still seeing errors after updating, please share your FluidAudio version, the exact error message, and a code snippet so we can investigate further.

**Comment by macayer** [comment]
I can confirm this has been resolved in the latest version, thank you. :)
